#!/usr/bin/env bash
# write a Bash script that will display information about subdomains.
# Information about server domains

track_domain() {
    # Check for a valid domain
    sub_domains=("www"  "lb-01" "web-01" "web-02")
    if [ -z "$2" ]; then
	for i in "${sub_domains[@]}"; do
	    dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
	done
    else
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
    fi
}

track_domain "$1" "$2"
