#!/bin/bash
# write a Bash script that will display information about subdomain 

display_domain_info() {
	#funtion that show information about a particular subdomain
	
	domain="$1"
	subdomain="$2"
	hostname="$subdomain.$domain"
	record_type=$(dig "$hostname" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	destination=$(dig "$hostname" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
	
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}
if [ $# -eq 1 ]; then
	subdomains=( "www" "lb-01" "web-01" "web-02" )
	for sub in "${subdomains[@]}"; do
		domain_info "$1" "$sub"
	done
elif [ $# -eq 2 ]; then
	display_domain_info "$1" "$2"
fi
