#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo service nginx start 
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
