#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# Nginx should be listening on port 80
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo apt-get install curl
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
