#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Test if Nginx returns "Hello World!" for the root path
curl -s http://localhost/ | grep -q "Hello World!"

# Print success message if the test passes
if [ $? -eq 0 ]; then
	    echo "Nginx successfully installed and configured."
    else
	        echo "Something went wrong with the Nginx configuration."
fi
