#!/usr/bin/env bash
# HAproxy load balancer configurations for webserver1 and webservers2

sudo apt-get update
sudo apt-get install -y haproxy

sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend lbserver
	bind *:80
	mode http
	default_backend webserver
backend webserver
	balance roundrobin
	server 218165-web-01 3.83.18.183:80 check
	server 218165-web-02 34.232.76.216:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy restart
