#!/usr/bin/env bash
# write a Bash script with the minimum number of commands to automate your code to listen a port 80

sudo sed -i "s/listen\s*8080;/listen 80;/"  etc/nginx/sites-available/default
service nginx restart
