#!/usr/bin/env bash

# debugging nginx not starting
# reconfiguring to default to listen to port 80, and not 8080

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
