#!/usr/bin/env bash
# write a Bash script with the minimum number of commands to automate your code to listen a port 80

sudo sed -i "s/8080/80/"  etc/nginx/sites-enabled/default

service nginx restart

echo "" | sudo tee /run/nginx.pid
