#!/usr/bin/env bash
# write a Bash script with the minimum number of commands to automate your code to listen a port 80

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
