#!/usr/bin/env bash
# a bash script that creates the file /var/run/myscript.

should_continue=true

cleanup()
{
        echo "cleaning up and terminating the process..."
        kill -QUIT "$pid"
        rm -f /var/run/myscript.pid
}
trap cleanup SIGQUIT SIGINT
trap 'touch /var/run/myscript.pid' EXIT
trap 'echo "I hate the kill command" SIGTERM' SIGTERM

while $should_continue
do
        echo "To infinity and beyond"
done

# Start a long-running process in the background
some_long_running_process & pid=$!
wait "$pid"
