#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process
# When passing the argument start
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process started
# When passing the argument stop
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Displays manage_my_process stopped
# When passing the argument restart
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process restarted

start()
{
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "Starting manage_my_process..."
	echo $! > /var/run/my_process.pid
    	echo "manage_my_process started."
}

stop()
{
	./manage_my_process &
    	echo "Stopping manage_my_process..."
    	kill $(cat /var/run/my_process.pid)
    	rm /var/run/my_process.pid
    	echo "manage_my_process stopped."
}

restart()
{
	kill "$(cat /var/run/my_process.pid)"

    rm /var/run/my_process.pid

    ./manage_my_process &

    touch /var/run/my_process.pid

    echo "$!" > /var/run/my_process.pid

    echo "manage_my_process restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
	        restart
	        ;;
        *)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
