#!/usr/bin/env bash
# A bash script that displays
#	To infinity and beyond indefinitely
#	With a sleep 2 in between each iteration
#	I am invincible!!! when receiving a SIGTERM 

trap 'echo "I am invincible!!!"; exit 0' SIGTERM

while true
do
  echo "To infinity and beyond!"
  sleep 2
done
