#!/usr/bin/env bash
# This script is displaying "Best School" 10 times.

i=0

while ((i < 10))
do
	if ((i == 4))
		then
			echo "good luck"
		elif((i == 8))
		then
			echo "bad luck"
		else
			echo "Best School"
	fi
	((i++));
done
