#!/usr/bin/env bash
# write a script that displays:
#	The contents of the current working directory
#	In a list
#	Where only the part of the name after the first dash is displayed

for i in *
do
	echo "$i"| cut -d"-" -f2
done
